import type { ValidationRule } from "./types";

export const FORM_NAME = "EquiTrust Certainty Select NJ Application";

/**
 * Centralized validation schema for EquiTrust Certainty Select NJ Application.
 * fieldPatterns are matched case-insensitively against AcroForm field names.
 */
export const validationSchema: ValidationRule[] = [
  // ── Page 1: Owner Information ──────────────────────────────────────────
  {
    id: "owner-first-name",
    formName: FORM_NAME,
    page: 1,
    section: "Owner Information",
    label: "Owner First Name",
    required: true,
    validationType: "text",
    severity: "required",
    fieldPatterns: ["ownerfirstname", "owner_first_name", "ownerfname", "firstname"],
  },
  {
    id: "owner-last-name",
    formName: FORM_NAME,
    page: 1,
    section: "Owner Information",
    label: "Owner Last Name",
    required: true,
    validationType: "text",
    severity: "required",
    fieldPatterns: ["ownerlastname", "owner_last_name", "ownerlname", "lastname"],
  },
  {
    id: "owner-dob",
    formName: FORM_NAME,
    page: 1,
    section: "Owner Information",
    label: "Owner Date of Birth",
    required: true,
    validationType: "date",
    severity: "required",
    fieldPatterns: ["ownerdob", "owner_dob", "dateofbirth", "dob"],
  },
  {
    id: "owner-ssn",
    formName: FORM_NAME,
    page: 1,
    section: "Owner Information",
    label: "Owner Social Security Number",
    required: true,
    validationType: "ssn",
    severity: "required",
    fieldPatterns: ["ownerssn", "owner_ssn", "ssn", "socialsecurity"],
  },
  {
    id: "owner-address",
    formName: FORM_NAME,
    page: 1,
    section: "Owner Information",
    label: "Owner Street Address",
    required: true,
    validationType: "text",
    severity: "required",
    fieldPatterns: ["owneraddress", "owner_address", "streetaddress", "address"],
  },
  {
    id: "owner-city",
    formName: FORM_NAME,
    page: 1,
    section: "Owner Information",
    label: "Owner City",
    required: true,
    validationType: "text",
    severity: "required",
    fieldPatterns: ["ownercity", "owner_city", "city"],
  },
  {
    id: "owner-state",
    formName: FORM_NAME,
    page: 1,
    section: "Owner Information",
    label: "Owner State",
    required: true,
    validationType: "selection",
    severity: "required",
    fieldPatterns: ["ownerstate", "owner_state", "state"],
  },
  {
    id: "owner-zip",
    formName: FORM_NAME,
    page: 1,
    section: "Owner Information",
    label: "Owner ZIP Code",
    required: true,
    validationType: "text",
    severity: "required",
    fieldPatterns: ["ownerzip", "owner_zip", "zipcode", "zip"],
  },
  {
    id: "owner-phone",
    formName: FORM_NAME,
    page: 1,
    section: "Owner Information",
    label: "Owner Phone Number",
    required: true,
    validationType: "phone",
    severity: "required",
    fieldPatterns: ["ownerphone", "owner_phone", "phonenumber", "phone"],
  },
  {
    id: "owner-email",
    formName: FORM_NAME,
    page: 1,
    section: "Owner Information",
    label: "Owner Email Address",
    required: false,
    validationType: "email",
    severity: "warning",
    fieldPatterns: ["owneremail", "owner_email", "email"],
  },

  // ── Page 1: Tax Qualification ────────────────────────────────────────
  {
    id: "tax-qualification",
    formName: FORM_NAME,
    page: 1,
    section: "Tax Qualification",
    label: "Tax Qualification Type (Qualified / Non-Qualified)",
    required: true,
    validationType: "selection",
    severity: "required",
    fieldPatterns: ["taxqual", "tax_qualification", "qualified", "nonqualified", "taxtype"],
  },

  // ── Page 2: Premium Payment ────────────────────────────────────────────
  {
    id: "premium-amount",
    formName: FORM_NAME,
    page: 2,
    section: "Premium Payment",
    label: "Premium Amount",
    required: true,
    validationType: "currency",
    severity: "required",
    fieldPatterns: ["premiumamount", "premium_amount", "premium", "contribution"],
  },
  {
    id: "payment-method",
    formName: FORM_NAME,
    page: 2,
    section: "Premium Payment",
    label: "Payment Method",
    required: true,
    validationType: "selection",
    severity: "required",
    fieldPatterns: ["paymentmethod", "payment_method", "paymethod"],
  },
  {
    id: "source-of-funds",
    formName: FORM_NAME,
    page: 2,
    section: "Source of Funds",
    label: "Source of Funds",
    required: true,
    validationType: "selection",
    severity: "required",
    fieldPatterns: ["sourceoffunds", "source_of_funds", "fundsource", "sourcefunds"],
  },
  {
    id: "source-of-funds-other",
    formName: FORM_NAME,
    page: 2,
    section: "Source of Funds",
    label: "Source of Funds — Other Description",
    required: true,
    validationType: "text",
    severity: "required",
    fieldPatterns: ["sourceoffundsother", "fundsourceother", "sourceother"],
    condition: {
      dependsOnRuleId: "source-of-funds",
      whenValues: ["other", "Other", "OTHER"],
    },
  },

  // ── Page 2: Existing Coverage / Replacement ──────────────────────────
  {
    id: "existing-coverage",
    formName: FORM_NAME,
    page: 2,
    section: "Existing Coverage / Replacement",
    label: "Do you have existing annuity or life insurance coverage?",
    required: true,
    validationType: "selection",
    severity: "required",
    fieldPatterns: ["existingcoverage", "existing_coverage", "havecoverage", "replacement"],
  },
  {
    id: "replacement-yes",
    formName: FORM_NAME,
    page: 2,
    section: "Existing Coverage / Replacement",
    label: "Replacement — Existing Policy Details",
    required: true,
    validationType: "text",
    severity: "required",
    fieldPatterns: ["replacementdetails", "existingpolicy", "policydetails", "replacement_info"],
    condition: {
      dependsOnRuleId: "existing-coverage",
      whenValues: ["yes", "Yes", "YES", "true", "True"],
    },
  },
  {
    id: "replacement-comparison",
    formName: FORM_NAME,
    page: 2,
    section: "Existing Coverage / Replacement",
    label: "Replacement Comparison Acknowledgment",
    required: true,
    validationType: "checkbox",
    severity: "required",
    fieldPatterns: ["replacementcomparison", "replacement_ack", "comparisonack"],
    condition: {
      dependsOnRuleId: "existing-coverage",
      whenValues: ["yes", "Yes", "YES", "true", "True"],
    },
  },

  // ── Page 3: Beneficiary Information ────────────────────────────────────
  {
    id: "primary-beneficiary-name",
    formName: FORM_NAME,
    page: 3,
    section: "Beneficiary Information",
    label: "Primary Beneficiary Name",
    required: true,
    validationType: "text",
    severity: "required",
    fieldPatterns: ["primarybeneficiary", "primary_beneficiary", "beneficiaryname", "benename"],
  },
  {
    id: "primary-beneficiary-relationship",
    formName: FORM_NAME,
    page: 3,
    section: "Beneficiary Information",
    label: "Primary Beneficiary Relationship",
    required: true,
    validationType: "text",
    severity: "required",
    fieldPatterns: ["beneficiaryrelationship", "benerelationship", "relationship"],
  },
  {
    id: "primary-beneficiary-percentage",
    formName: FORM_NAME,
    page: 3,
    section: "Beneficiary Information",
    label: "Primary Beneficiary Percentage",
    required: true,
    validationType: "text",
    severity: "required",
    fieldPatterns: ["beneficiarypercentage", "benepercentage", "percentage"],
  },
  {
    id: "contingent-beneficiary",
    formName: FORM_NAME,
    page: 3,
    section: "Beneficiary Information",
    label: "Contingent Beneficiary Name",
    required: false,
    validationType: "text",
    severity: "warning",
    fieldPatterns: ["contingentbeneficiary", "contingent_beneficiary", "secondarybeneficiary"],
  },

  // ── Page 3: Certainty Select Guarantee Period ──────────────────────────
  {
    id: "guarantee-period",
    formName: FORM_NAME,
    page: 3,
    section: "Certainty Select Guarantee Period",
    label: "Guarantee Period Selection",
    required: true,
    validationType: "selection",
    severity: "required",
    fieldPatterns: ["guaranteeperiod", "guarantee_period", "certaintyselect", "guarantee"],
  },

  // ── Page 4: Financial Needs Analysis ───────────────────────────────────
  {
    id: "fna-completed",
    formName: FORM_NAME,
    page: 4,
    section: "Financial Needs Analysis",
    label: "Financial Needs Analysis Completed",
    required: true,
    validationType: "checkbox",
    severity: "required",
    fieldPatterns: ["fnacompleted", "fna_completed", "financialneeds", "fna"],
  },
  {
    id: "fna-objectives",
    formName: FORM_NAME,
    page: 4,
    section: "Financial Needs Analysis",
    label: "Investment Objectives Documented",
    required: true,
    validationType: "checkbox",
    severity: "required",
    fieldPatterns: ["investmentobjectives", "fnaobjectives", "objectives"],
  },
  {
    id: "fna-risk-tolerance",
    formName: FORM_NAME,
    page: 4,
    section: "Financial Needs Analysis",
    label: "Risk Tolerance Assessment",
    required: true,
    validationType: "selection",
    severity: "required",
    fieldPatterns: ["risktolerance", "risk_tolerance", "risklevel"],
  },

  // ── Page 5: Signatures & Disclosures ───────────────────────────────────
  {
    id: "owner-signature",
    formName: FORM_NAME,
    page: 5,
    section: "Owner Signature",
    label: "Owner Signature",
    required: true,
    validationType: "signature",
    severity: "required",
    fieldPatterns: ["ownersignature", "owner_signature", "ownersig"],
  },
  {
    id: "owner-signature-date",
    formName: FORM_NAME,
    page: 5,
    section: "Owner Signature",
    label: "Owner Signature Date",
    required: true,
    validationType: "date",
    severity: "required",
    fieldPatterns: ["ownersignaturedate", "owner_sig_date", "ownerdate", "owner_signature_date"],
  },
  {
    id: "agent-signature",
    formName: FORM_NAME,
    page: 5,
    section: "Agent Signature",
    label: "Agent / Producer Signature",
    required: true,
    validationType: "signature",
    severity: "required",
    fieldPatterns: ["agentsignature", "agent_signature", "producersignature", "agentsig"],
  },
  {
    id: "agent-signature-date",
    formName: FORM_NAME,
    page: 5,
    section: "Agent Signature",
    label: "Agent / Producer Signature Date",
    required: true,
    validationType: "date",
    severity: "required",
    fieldPatterns: ["agentsignaturedate", "agent_sig_date", "agentdate", "agent_signature_date"],
  },
  {
    id: "disclosure-signature",
    formName: FORM_NAME,
    page: 5,
    section: "Disclosure Statement",
    label: "Disclosure Statement Signature",
    required: true,
    validationType: "signature",
    severity: "required",
    fieldPatterns: ["disclosuresignature", "disclosure_signature", "disclosuresig"],
  },
  {
    id: "disclosure-acknowledgment",
    formName: FORM_NAME,
    page: 5,
    section: "Disclosure Statement",
    label: "Disclosure Statement Acknowledgment",
    required: true,
    validationType: "checkbox",
    severity: "required",
    fieldPatterns: ["disclosureack", "disclosure_ack", "disclosureacknowledgment"],
  },

  // ── Page 6: Agent / Producer Disclosure ────────────────────────────────
  {
    id: "agent-name",
    formName: FORM_NAME,
    page: 6,
    section: "Agent / Producer Disclosure",
    label: "Agent / Producer Name",
    required: true,
    validationType: "text",
    severity: "required",
    fieldPatterns: ["agentname", "agent_name", "producername", "producer_name"],
  },
  {
    id: "agent-license",
    formName: FORM_NAME,
    page: 6,
    section: "Agent / Producer Disclosure",
    label: "Agent License Number",
    required: true,
    validationType: "text",
    severity: "required",
    fieldPatterns: ["agentlicense", "agent_license", "licensenumber", "licenseno"],
  },
  {
    id: "agent-compensation-disclosure",
    formName: FORM_NAME,
    page: 6,
    section: "Agent / Producer Disclosure",
    label: "Compensation Disclosure Acknowledgment",
    required: true,
    validationType: "checkbox",
    severity: "required",
    fieldPatterns: ["compensationdisclosure", "compensation_disclosure", "compdisclosure"],
  },
  {
    id: "agent-affiliation-disclosure",
    formName: FORM_NAME,
    page: 6,
    section: "Agent / Producer Disclosure",
    label: "Affiliation / Conflict of Interest Disclosure",
    required: true,
    validationType: "checkbox",
    severity: "warning",
    fieldPatterns: ["affiliationdisclosure", "conflictofinterest", "affiliation"],
  },
];
