import type { ReviewItemLocation } from "../types";

export const FORM_NAME = "EquiTrust MarketEarly Income Index NJ Application Packet";

export type RequiredStatus = "required" | "conditional" | "supporting";

export interface PacketPage {
  pageRange: string;
  documentName: string;
  sectionName: string;
  purpose: string;
  requiredStatus: RequiredStatus;
  expectedFields: string[];
  expectedCheckboxes: string[];
  expectedSignatures: string[];
  expectedDates: string[];
  manualReviewHint: string;
}

export interface DocumentTemplate {
  templateName: string;
  packetStructure: PacketPage[];
  reviewItemLocations: Record<string, ReviewItemLocation>;
}

export const equitrustMarketEarlyNJ: DocumentTemplate = {
  templateName: "EquiTrust MarketEarly Income Index NJ",
  packetStructure: [
    {
      pageRange: "1",
      documentName: "SFG Internal Cover Sheet (Pink Sheet)",
      sectionName: "Case Routing / Tracking",
      purpose: "Internal SFG case-tracking sheet summarizing the case; not a carrier form.",
      requiredStatus: "supporting",
      expectedFields: ["Client name", "Advisor name", "Carrier", "Product", "Term", "Premium", "Transfer company", "Effective date", "Policy number", "Final amount"],
      expectedCheckboxes: ["Delivery method (Carrier/Upline)", "Submission method (Emailed/Faxed/E-App)", "Qualified / Non-Qualified", "Transfer/1035x", "Smart Office / TP in File"],
      expectedSignatures: [],
      expectedDates: ["SFG In Date", "Effective Date"],
      manualReviewHint: "Internal use only. Cross-check product, premium, and policy number against the carrier application on page 2-3.",
    },
    {
      pageRange: "2",
      documentName: "Individual Annuity Application (ICC19-ET-APP)",
      sectionName: "Section A - Owner Info / Section B - Annuitant Info",
      purpose: "Captures owner and annuitant identity and contact details.",
      requiredStatus: "required",
      expectedFields: ["Product name", "Agent name / phone / agent number / split %", "Owner full name", "Owner gender / age", "Owner SSN (presence only)", "Owner address / phone / email", "Annuitant full name (if different from owner)"],
      expectedCheckboxes: ["Type of ownership", "Marital status"],
      expectedSignatures: [],
      expectedDates: [],
      manualReviewHint: "Owner and annuitant are often the same person; Section B may mirror Section A.",
    },
    {
      pageRange: "3",
      documentName: "Individual Annuity Application (ICC19-ET-APP)",
      sectionName: "Section C-G: Tax Qualification / Premium / Existing Coverage / Beneficiary / Special Requests",
      purpose: "Establishes tax status, premium amount, replacement flag, and beneficiary designation.",
      requiredStatus: "required",
      expectedFields: ["Total premium amount", "Anticipated external transfer amount", "Beneficiary name / share % / relationship"],
      expectedCheckboxes: ["Tax qualification (Non-Qualified / IRA / Roth / etc.)", "Existing coverage / replacement Yes-No", "Primary / Contingent beneficiary"],
      expectedSignatures: [],
      expectedDates: [],
      manualReviewHint: "If Section E replacement = Yes, a Replacement Notice and Product Comparison must appear later in the packet.",
    },
    {
      pageRange: "4",
      documentName: "Individual Annuity Application (ICC19-ET-APP)",
      sectionName: "Section H-J: Notice / Signatures / Agent Certification",
      purpose: "Owner and agent execution of the core application.",
      requiredStatus: "required",
      expectedFields: ["Replacement reason", "Source of funds to be replaced"],
      expectedCheckboxes: ["Replacement Yes-No", "Source-of-funds type", "Agent certification items"],
      expectedSignatures: ["Owner signature", "Agent/Producer signature"],
      expectedDates: ["Owner signature date", "Agent signature date"],
      manualReviewHint: "Primary application signature page. Confirm both owner and agent signatures plus dates are present.",
    },
    {
      pageRange: "5-8",
      documentName: "Disclosure Statement (ET-MKE-1101NJ)",
      sectionName: "Interest Crediting / Liquidity & Surrender / Income Rider / Index Disclosures",
      purpose: "Product disclosure pages.",
      requiredStatus: "required",
      expectedFields: [],
      expectedCheckboxes: [],
      expectedSignatures: [],
      expectedDates: [],
      manualReviewHint: "Informational pages, no fields to validate. Signature for this disclosure is on page 9.",
    },
    {
      pageRange: "9",
      documentName: "Disclosure Statement (ET-MKE-1101NJ)",
      sectionName: "Initial Premium Allocation - Required",
      purpose: "Captures premium allocation and owner disclosure acknowledgment signature.",
      requiredStatus: "required",
      expectedFields: ["Allocation percentage per index account", "Allocation total (must equal 100%)"],
      expectedCheckboxes: ["Qualified / Non-Qualified"],
      expectedSignatures: ["Owner signature", "Agent/Producer signature"],
      expectedDates: ["Owner signature date", "Agent signature date"],
      manualReviewHint: "Verify allocation percentages sum to exactly 100% and the owner disclosure signature/date are present.",
    },
    {
      pageRange: "10-12",
      documentName: "Financial Needs Analysis (ET-2506)",
      sectionName: "Financial Profile / Financial Situation / Annuity Objectives",
      purpose: "Suitability data.",
      requiredStatus: "required",
      expectedFields: ["Annual income range", "Annual expense range", "Federal tax bracket", "Net worth ranges"],
      expectedCheckboxes: ["Employment status", "Income source(s)", "Risk tolerance", "Product experience", "Time horizon", "Objectives", "Distribution method", "Source of funds"],
      expectedSignatures: [],
      expectedDates: [],
      manualReviewHint: "Risk tolerance is on page 10 (Q6); distribution objectives on page 12 (Q13-Q15); source of funds on page 12 (Q16).",
    },
    {
      pageRange: "13-14",
      documentName: "Insurance Agent/Producer Disclosure for Annuities (ET-2506)",
      sectionName: "Producer Info / Products / Acknowledgments & Signatures",
      purpose: "Producer licensing and compensation disclosure plus suitability acknowledgment.",
      requiredStatus: "required",
      expectedFields: ["Agent full name", "Business phone", "National Producer Number", "State", "Owner name", "Basis for recommendation"],
      expectedCheckboxes: ["Product types offered", "Number of insurers authorized", "Compensation method", "Statement of purchaser", "Recommendation basis"],
      expectedSignatures: ["Owner/Applicant signature", "Agent/Producer signature"],
      expectedDates: ["Owner signature date", "Agent signature date"],
      manualReviewHint: "Agent/Producer info on page 13; acknowledgment and signatures on page 14.",
    },
    {
      pageRange: "15-18",
      documentName: "Transfer/1035 Exchange Form (ET-TRN/1035-4902)",
      sectionName: "Current Contract / Transfer Instructions / Exchange Type",
      purpose: "Authorizes transfer from existing carrier. REPEATED once per replaced contract.",
      requiredStatus: "conditional",
      expectedFields: ["Distributing company name", "Contract/policy number being exchanged", "Owner / annuitant info", "Owner address"],
      expectedCheckboxes: ["Account type", "Transfer timing", "1035 Exchange vs Non-Qualified Transfer", "Full / Partial"],
      expectedSignatures: ["Owner signature"],
      expectedDates: ["Owner signature date"],
      manualReviewHint: "Appears once per existing contract being replaced. Page numbers approximate.",
    },
    {
      pageRange: "19-22",
      documentName: "Important Notice: Replacement of Life Insurance or Annuities (ET-RPL-4900)",
      sectionName: "Replacement Questions / Notice",
      purpose: "NJ-required replacement disclosure. REPEATED once per replaced contract.",
      requiredStatus: "conditional",
      expectedFields: ["Existing insurer name", "Existing contract number", "Replaced (R) or Financing (F) indicator", "Reason for replacement"],
      expectedCheckboxes: ["Question 1 Yes-No", "Question 2 Yes-No", "Read-aloud initials"],
      expectedSignatures: ["Applicant signature", "Agent signature"],
      expectedDates: ["Applicant signature date", "Agent signature date"],
      manualReviewHint: "Required only when replacement = Yes on application Section E. Repeats per contract.",
    },
    {
      pageRange: "23-26",
      documentName: "Disclosure & Comparison of Products (ET-MKE-4901)",
      sectionName: "Existing vs Proposed Annuity / Life Replacement Section",
      purpose: "Side-by-side comparison. REPEATED once per replaced contract.",
      requiredStatus: "conditional",
      expectedFields: ["Replaced company / product / contract number", "Estimated surrender loss", "Existing accumulation & surrender values", "Benefit base / IBR details", "Reason for replacement"],
      expectedCheckboxes: ["Generic contract type", "MVA Yes-No", "Return of premium Yes-No", "Nursing home / terminal illness riders", "Income benefit rider Yes-No"],
      expectedSignatures: ["Owner signature", "Agent/Producer signature"],
      expectedDates: ["Owner signature date", "Agent signature date"],
      manualReviewHint: "Required when replacement = Yes. Repeats per contract.",
    },
    {
      pageRange: "27",
      documentName: "Authorization to Hold Issue for Multiple Premiums (ET-2504)",
      sectionName: "Flexible Premium Hold Authorization",
      purpose: "Requests that the contract not be issued until all premium has been received.",
      requiredStatus: "conditional",
      expectedFields: ["Owner name"],
      expectedCheckboxes: [],
      expectedSignatures: ["Owner signature", "Agent/Producer signature"],
      expectedDates: ["Owner signature date", "Agent signature date"],
      manualReviewHint: "Used for flexible-premium / multi-transfer cases where premium arrives in pieces.",
    },
    {
      pageRange: "28",
      documentName: "Electronic Transactions and Disclosures Agreement (ET-ELEDISC)",
      sectionName: "Electronic Delivery Consent",
      purpose: "Records the owner's consent (or refusal) for electronic delivery.",
      requiredStatus: "supporting",
      expectedFields: ["Owner name", "Email address", "Contract number"],
      expectedCheckboxes: ["Consent Yes-No"],
      expectedSignatures: ["Owner signature"],
      expectedDates: ["Owner signature date"],
      manualReviewHint: "Check whether consent box and signature are consistent (Yes consent vs No consent).",
    },
    {
      pageRange: "29",
      documentName: "Trail Commission Election Form (ET-COMMELECT)",
      sectionName: "Commission Payment Option",
      purpose: "Agent-only election of commission payment option.",
      requiredStatus: "supporting",
      expectedFields: ["Agent name / number", "Owner name", "Product applied for", "Estimated premium"],
      expectedCheckboxes: ["Option A / B / C"],
      expectedSignatures: ["Agent signature"],
      expectedDates: ["Agent signature date"],
      manualReviewHint: "Agent-facing form. No owner signature required.",
    },
    {
      pageRange: "30",
      documentName: "Stable-Lite Verification Call Notice (ET-STBLTYCLS)",
      sectionName: "Welcome / Verification Call Notice",
      purpose: "Notifies the client they may receive a verification call from EquiTrust.",
      requiredStatus: "supporting",
      expectedFields: ["Product type", "Surrender-charge period", "Liquidity provisions", "Source of funds"],
      expectedCheckboxes: [],
      expectedSignatures: [],
      expectedDates: [],
      manualReviewHint: "Agent fills the blanks to prep client for the verification call. No signature.",
    },
    {
      pageRange: "31",
      documentName: "Ink Signature Requirements (ET-ISR)",
      sectionName: "Reference",
      purpose: "Reference list of which forms may require wet/ink signatures.",
      requiredStatus: "supporting",
      expectedFields: [],
      expectedCheckboxes: [],
      expectedSignatures: [],
      expectedDates: [],
      manualReviewHint: "Static reference page. Nothing to validate.",
    },
    {
      pageRange: "32",
      documentName: "Privacy Notice (ET-PRI-4905)",
      sectionName: "Privacy Disclosure",
      purpose: "Required privacy practices disclosure.",
      requiredStatus: "supporting",
      expectedFields: [],
      expectedCheckboxes: [],
      expectedSignatures: [],
      expectedDates: [],
      manualReviewHint: "Static disclosure page. Nothing to validate.",
    },
    {
      pageRange: "33",
      documentName: "Disclosure & Comparison of Products (ET-MKE-4901) - DUPLICATE",
      sectionName: "Existing vs Proposed Annuity (ink-signed/annotated copy)",
      purpose: "Duplicate or ink-signed copy of the Product Comparison form (see pages 23-26).",
      requiredStatus: "supporting",
      expectedFields: ["Same as pages 23-26"],
      expectedCheckboxes: ["Same as pages 23-26"],
      expectedSignatures: ["Owner signature (handwritten/annotated)"],
      expectedDates: ["Owner signature date"],
      manualReviewHint: "Duplicate of an earlier Product Comparison page with handwritten annotations. Do not double-count as a separate contract.",
    },
    {
      pageRange: "34",
      documentName: "Fax Send Result Report (Carrier MFP)",
      sectionName: "Transmission Confirmation",
      purpose: "Proof-of-fax confirmation showing a transfer/1035 form was sent to the prior carrier.",
      requiredStatus: "supporting",
      expectedFields: ["Receiving company name", "Receiving fax number", "Transmission date/time", "Result (OK/fail)"],
      expectedCheckboxes: [],
      expectedSignatures: [],
      expectedDates: ["Transmission date"],
      manualReviewHint: "Operational artifact confirming the transfer fax went through. Confirm 'Complete' / 'OK' result.",
    },
  ],
  reviewItemLocations: {
    ownerInformation: {
      label: "Owner Information",
      expectedDocument: "Individual Annuity Application (ICC19-ET-APP)",
      typicalLocation: "Section A, top half of page",
      typicalPageRange: "2",
      pageConfidence: "fixed",
      manualReviewHint: "Owner block is the upper-left of Section A.",
    },
    ownerSsnPresence: {
      label: "Owner SSN presence only",
      expectedDocument: "Individual Annuity Application (ICC19-ET-APP)",
      typicalLocation: "Section A, directly under owner full name",
      typicalPageRange: "2",
      pageConfidence: "fixed",
      manualReviewHint: "Presence/absence check ONLY. Do not transcribe the number.",
    },
    jointOwner: {
      label: "Joint Owner",
      expectedDocument: "Individual Annuity Application (ICC19-ET-APP)",
      typicalLocation: "Section A, right-hand column",
      typicalPageRange: "2",
      pageConfidence: "fixed",
      manualReviewHint: "Often blank. Not available for qualified plans. Confirm blank vs populated.",
    },
    annuitantInformation: {
      label: "Annuitant Information",
      expectedDocument: "Individual Annuity Application (ICC19-ET-APP)",
      typicalLocation: "Section B, lower half of page",
      typicalPageRange: "2",
      pageConfidence: "fixed",
      manualReviewHint: "If blank, annuitant defaults to owner. Confirm whether it mirrors Section A.",
    },
    beneficiaryDesignation: {
      label: "Beneficiary Designation",
      expectedDocument: "Individual Annuity Application (ICC19-ET-APP)",
      typicalLocation: "Section F",
      typicalPageRange: "3",
      pageConfidence: "fixed",
      manualReviewHint: "Check share percentages total 100% and primary/contingent boxes are marked.",
    },
    premiumPayment: {
      label: "Premium Payment",
      expectedDocument: "Individual Annuity Application (ICC19-ET-APP)",
      typicalLocation: "Section D",
      typicalPageRange: "3",
      pageConfidence: "fixed",
      manualReviewHint: "Cross-check total premium against transfer amounts and cover sheet.",
    },
    productSelection: {
      label: "Product Selection",
      expectedDocument: "Individual Annuity Application (ICC19-ET-APP)",
      typicalLocation: "Top 'Product' field above Section A",
      typicalPageRange: "2",
      pageConfidence: "fixed",
      manualReviewHint: "Should read 'MarketEarly Income Index'. Confirm match with disclosure and cover sheet.",
    },
    taxQualification: {
      label: "Tax Qualification",
      expectedDocument: "Individual Annuity Application (ICC19-ET-APP)",
      typicalLocation: "Section C",
      typicalPageRange: "3",
      pageConfidence: "fixed",
      manualReviewHint: "Exactly one box should be checked (Non-Qualified, IRA, Roth, etc.).",
    },
    existingCoverage: {
      label: "Existing Coverage / Replacement Questions",
      expectedDocument: "Individual Annuity Application (ICC19-ET-APP)",
      typicalLocation: "Section E",
      typicalPageRange: "3",
      pageConfidence: "fixed",
      manualReviewHint: "If replacement = Yes, replacement notice and product comparison forms are required later.",
    },
    sourceOfFunds: {
      label: "Source of Funds",
      expectedDocument: "Financial Needs Analysis (ET-2506)",
      typicalLocation: "Q16 (FNA); also App Section J replacement source",
      typicalPageRange: "12 (primary), 4 (secondary)",
      pageConfidence: "fixed",
      manualReviewHint: "FNA Q16 is the primary source-of-funds answer; cross-check with application Section J.",
    },
    replacementQuestions: {
      label: "Replacement Questions",
      expectedDocument: "Important Notice: Replacement of Life Insurance or Annuities (ET-RPL-4900)",
      typicalLocation: "Questions 1 & 2 near the top of the notice",
      typicalPageRange: "19-22",
      pageConfidence: "approximate",
      manualReviewHint: "Required only if replacement = Yes. Repeats once per replaced contract; page numbers shift accordingly.",
    },
    transfer: {
      label: "Transfer",
      expectedDocument: "Transfer/1035 Exchange Form (ET-TRN/1035-4902)",
      typicalLocation: "Sections 1-2 (Current Contract / Transfer Instructions)",
      typicalPageRange: "15-18",
      pageConfidence: "approximate",
      manualReviewHint: "One 2-page set per replaced contract. Confirm distributing company and contract number match the Replacement Notice.",
    },
    sec1035Exchange: {
      label: "1035 Exchange",
      expectedDocument: "Transfer/1035 Exchange Form (ET-TRN/1035-4902)",
      typicalLocation: "Section 3, Part A (1035 Exchange)",
      typicalPageRange: "15-18",
      pageConfidence: "approximate",
      manualReviewHint: "Confirm Full vs Partial selection and that Part A (not B/C/D) is used for a like-to-like 1035.",
    },
    financialNeedsAnalysis: {
      label: "Financial Needs Analysis",
      expectedDocument: "Financial Needs Analysis (ET-2506)",
      typicalLocation: "Entire form",
      typicalPageRange: "10-12",
      pageConfidence: "fixed",
      manualReviewHint: "Three-page suitability form. Confirm all applicable sections are completed.",
    },
    riskTolerance: {
      label: "Risk Tolerance",
      expectedDocument: "Financial Needs Analysis (ET-2506)",
      typicalLocation: "Question 6",
      typicalPageRange: "10",
      pageConfidence: "fixed",
      manualReviewHint: "One of Conservative / Moderate / Aggressive should be checked.",
    },
    distributionObjectives: {
      label: "Distribution Objectives",
      expectedDocument: "Financial Needs Analysis (ET-2506)",
      typicalLocation: "Questions 13-15",
      typicalPageRange: "12",
      pageConfidence: "fixed",
      manualReviewHint: "Covers how the annuity meets objectives, anticipated distributions, and distribution method.",
    },
    initialPremiumAllocation: {
      label: "Initial Premium Allocation",
      expectedDocument: "Disclosure Statement (ET-MKE-1101NJ)",
      typicalLocation: "'Initial Premium Allocation - Required' box",
      typicalPageRange: "9",
      pageConfidence: "fixed",
      manualReviewHint: "Each index account has a percentage; confirm each is a whole number.",
    },
    allocationTotalEquals100: {
      label: "Allocation Total Equals 100%",
      expectedDocument: "Disclosure Statement (ET-MKE-1101NJ)",
      typicalLocation: "Total row at the bottom of the allocation box",
      typicalPageRange: "9",
      pageConfidence: "fixed",
      manualReviewHint: "Sum of all allocation percentages must equal exactly 100%.",
    },
    productDisclosureSignature: {
      label: "Product Disclosure Signature",
      expectedDocument: "Disclosure Statement (ET-MKE-1101NJ)",
      typicalLocation: "Owner Statement signature block",
      typicalPageRange: "9",
      pageConfidence: "fixed",
      manualReviewHint: "Owner signature acknowledging the product disclosure.",
    },
    productDisclosureSignatureDate: {
      label: "Product Disclosure Signature Date",
      expectedDocument: "Disclosure Statement (ET-MKE-1101NJ)",
      typicalLocation: "Beside the owner signature in the Owner Statement block",
      typicalPageRange: "9",
      pageConfidence: "fixed",
      manualReviewHint: "Date should be present next to the disclosure signature.",
    },
    ownerSignature: {
      label: "Owner Signature",
      expectedDocument: "Individual Annuity Application (ICC19-ET-APP)",
      typicalLocation: "Section I (Signatures)",
      typicalPageRange: "4",
      pageConfidence: "fixed",
      manualReviewHint: "Primary owner signature is on page 4; owner also signs pages 9 and 14.",
    },
    ownerSignatureDate: {
      label: "Owner Signature Date",
      expectedDocument: "Individual Annuity Application (ICC19-ET-APP)",
      typicalLocation: "Beside the owner signature in Section I",
      typicalPageRange: "4",
      pageConfidence: "fixed",
      manualReviewHint: "Confirm the date matches other signature dates in the packet.",
    },
    agentSignature: {
      label: "Agent Signature",
      expectedDocument: "Individual Annuity Application (ICC19-ET-APP)",
      typicalLocation: "Section J (Agent Certification)",
      typicalPageRange: "4",
      pageConfidence: "fixed",
      manualReviewHint: "Primary agent signature is on page 4; agent also signs pages 9 and 14.",
    },
    agentSignatureDate: {
      label: "Agent Signature Date",
      expectedDocument: "Individual Annuity Application (ICC19-ET-APP)",
      typicalLocation: "Beside the agent signature in Section J",
      typicalPageRange: "4",
      pageConfidence: "fixed",
      manualReviewHint: "Confirm presence and consistency with owner date.",
    },
    agentProducerInformation: {
      label: "Agent / Producer Information",
      expectedDocument: "Insurance Agent/Producer Disclosure for Annuities (ET-2506)",
      typicalLocation: "Section 1 (Insurance Agent Information)",
      typicalPageRange: "13",
      pageConfidence: "fixed",
      manualReviewHint: "Confirm name, business phone, National Producer Number, and state are present.",
    },
    agentProducerDisclosure: {
      label: "Agent/Producer Disclosure",
      expectedDocument: "Insurance Agent/Producer Disclosure for Annuities (ET-2506)",
      typicalLocation: "Entire form",
      typicalPageRange: "13-14",
      pageConfidence: "fixed",
      manualReviewHint: "Two-page disclosure; signatures are on page 14.",
    },
    acknowledgmentsAndSignatures: {
      label: "Acknowledgments and Signatures",
      expectedDocument: "Insurance Agent/Producer Disclosure for Annuities (ET-2506)",
      typicalLocation: "Bottom 'Acknowledgements and Signatures' section",
      typicalPageRange: "14",
      pageConfidence: "fixed",
      manualReviewHint: "Confirm Statement of Purchaser, recommendation basis, and both signatures with dates.",
    },
    disclosureComparison: {
      label: "Disclosure & Comparison of Products",
      expectedDocument: "Disclosure & Comparison of Products (ET-MKE-4901)",
      typicalLocation: "Existing vs Proposed Annuity section",
      typicalPageRange: "23-26",
      pageConfidence: "approximate",
      manualReviewHint: "Required when replacement = Yes. Repeats per contract; page numbers are approximate.",
    },
    authorizationHoldIssue: {
      label: "Authorization to Hold Issue for Multiple Premiums",
      expectedDocument: "Authorization to Hold Issue for Multiple Premiums (ET-2504)",
      typicalLocation: "Flexible Premium Hold Authorization",
      typicalPageRange: "27",
      pageConfidence: "approximate",
      manualReviewHint: "Used for flexible-premium / multi-transfer cases where premium arrives in pieces.",
    },
    electronicTransactions: {
      label: "Electronic Transactions and Disclosures Agreement",
      expectedDocument: "Electronic Transactions and Disclosures Agreement (ET-ELEDISC)",
      typicalLocation: "Electronic Delivery Consent",
      typicalPageRange: "28",
      pageConfidence: "approximate",
      manualReviewHint: "Check whether consent box and signature are consistent (Yes consent vs No consent).",
    },
    trailCommissionElection: {
      label: "Trail Commission Election",
      expectedDocument: "Trail Commission Election Form (ET-COMMELECT)",
      typicalLocation: "Commission Payment Option",
      typicalPageRange: "29",
      pageConfidence: "approximate",
      manualReviewHint: "Agent-facing form. No owner signature required.",
    },
    privacyNotice: {
      label: "Privacy Notice",
      expectedDocument: "Privacy Notice (ET-PRI-4905)",
      typicalLocation: "Privacy Disclosure",
      typicalPageRange: "32",
      pageConfidence: "approximate",
      manualReviewHint: "Static disclosure page. Confirm included in packet.",
    },
    faxConfirmation: {
      label: "Fax Confirmation / Supporting Documents",
      expectedDocument: "Fax Send Result Report (Carrier MFP)",
      typicalLocation: "Transmission Confirmation",
      typicalPageRange: "34",
      pageConfidence: "approximate",
      manualReviewHint: "Operational artifact confirming the transfer fax went through. Confirm 'Complete' / 'OK' result.",
    },
  },
};

export const RULE_LOCATION_KEYS: Record<string, keyof typeof equitrustMarketEarlyNJ.reviewItemLocations> = {
  "owner-info": "ownerInformation",
  "annuitant-info": "annuitantInformation",
  "owner-ssn": "ownerSsnPresence",
  "product-name": "productSelection",
  "agent-info": "agentProducerInformation",
  "tax-qualification": "taxQualification",
  "premium-payment": "premiumPayment",
  "existing-coverage": "existingCoverage",
  beneficiary: "beneficiaryDesignation",
  "owner-signature": "ownerSignature",
  "owner-signature-date": "ownerSignatureDate",
  "agent-signature": "agentSignature",
  "agent-signature-date": "agentSignatureDate",
  "pds-signature": "productDisclosureSignature",
  "pds-signature-date": "productDisclosureSignatureDate",
  "allocation-page": "initialPremiumAllocation",
  "allocation-100": "allocationTotalEquals100",
  "fna-page-1": "financialNeedsAnalysis",
  "fna-risk": "riskTolerance",
  "fna-source": "sourceOfFunds",
  "fna-distribution": "distributionObjectives",
  "fna-source-other-explain": "sourceOfFunds",
  "agent-disclosure": "agentProducerDisclosure",
  acknowledgments: "acknowledgmentsAndSignatures",
  "replacement-notice": "replacementQuestions",
  "disclosure-comparison": "disclosureComparison",
  "transfer-form": "transfer",
};

export function getLocationForRule(ruleId: string): ReviewItemLocation | null {
  const key = RULE_LOCATION_KEYS[ruleId];
  if (!key) return null;
  return equitrustMarketEarlyNJ.reviewItemLocations[key] ?? null;
}
