import type { ConfigurableRuleDefinition } from "../rule-config";

/**
 * EquiTrust MarketEarly NJ — full validation rule set.
 * Processor-oriented scoped rules; compiled via compileConfigurableRules().
 */
export const EQUITRUST_CONFIGURABLE_RULES: ConfigurableRuleDefinition[] = [
  // ── Individual Application: Owner / Annuitant ──────────────────────────────
  {
    id: "owner-info",
    label: "Owner Information",
    section: "Owner Information",
    severity: "required",
    kind: "label_value",
    requiredDocument: "individual_application",
    expectedPageSubtype: "owner_info",
    requiredSection: "owner information|section a",
    evidence: ["value"],
    labelPatterns: ["owner information", "owner name", "first name", "last name"],
    valuePatterns: ["first name|last name|owner name"],
    locationKey: "ownerInformation",
    confidenceThreshold: 0.85,
  },
  {
    id: "annuitant-info",
    label: "Annuitant Information",
    section: "Annuitant Information",
    severity: "required",
    kind: "label_value",
    requiredDocument: "individual_application",
    expectedPageSubtype: "owner_info",
    requiredSection: "annuitant information|section b",
    evidence: ["value"],
    labelPatterns: ["annuitant information", "annuitant name"],
    valuePatterns: ["annuitant name|annuitant information"],
    locationKey: "annuitantInformation",
    confidenceThreshold: 0.85,
  },
  {
    id: "owner-ssn",
    label: "Owner SSN (presence only)",
    section: "Owner Information",
    severity: "required",
    kind: "label_value",
    requiredDocument: "individual_application",
    expectedPageSubtype: "owner_info",
    requiredSection: "owner information|section a|social security",
    evidence: ["value"],
    labelPatterns: ["social security", "ssn", "tax id"],
    valuePatterns: ["\\d{3}[-\\s]?\\d{2}[-\\s]?\\d{4}|social security"],
    locationKey: "ownerSsnPresence",
    confidenceThreshold: 0.8,
  },
  {
    id: "product-name",
    label: "Product Name",
    section: "Product Selection",
    severity: "required",
    kind: "label_value",
    requiredDocument: "individual_application",
    expectedPageSubtype: "owner_info",
    requiredSection: "product|section a",
    evidence: ["value"],
    labelPatterns: ["product name", "marketearly", "certainty select"],
    valuePatterns: ["marketearly|certainty select|income index"],
    locationKey: "productSelection",
    confidenceThreshold: 0.85,
  },
  {
    id: "agent-info",
    label: "Agent / Producer Information",
    section: "Agent Information",
    severity: "required",
    kind: "label_value",
    requiredDocument: "individual_application",
    expectedPageSubtype: "owner_info",
    requiredSection: "agent|producer|section a",
    evidence: ["value"],
    labelPatterns: ["agent name", "producer name", "agent number", "national producer"],
    valuePatterns: ["agent|producer|npn|national producer"],
    locationKey: "agentProducerInformation",
    confidenceThreshold: 0.8,
  },

  // ── Application Page 2: Tax / Premium / Beneficiary / Replacement Qs ─────
  {
    id: "tax-qualification",
    label: "Tax Qualification",
    section: "Tax Qualification",
    severity: "required",
    kind: "label_value",
    requiredDocument: "individual_application",
    expectedPageSubtype: "premium",
    requiredSection: "tax qualification|section c",
    evidence: ["value", "checkbox"],
    labelPatterns: ["tax qualification", "tax qualif", "ira", "non-qualified", "roth"],
    valuePatterns: ["ira|non-?qualified|roth|tax qualification"],
    locationKey: "taxQualification",
    confidenceThreshold: 0.85,
  },
  {
    id: "premium-payment",
    label: "Premium Payment Details",
    section: "Premium Payment",
    severity: "required",
    kind: "label_value",
    requiredDocument: "individual_application",
    expectedPageSubtype: "premium",
    requiredSection: "premium payment|section d|total premium",
    evidence: ["value"],
    labelPatterns: ["premium payment", "total premium", "initial premium", "anticipated"],
    valuePatterns: ["\\$[\\d,]+|premium amount|total premium"],
    locationKey: "premiumPayment",
    confidenceThreshold: 0.85,
  },
  {
    id: "existing-coverage",
    label: "Existing Coverage / Replacement Questions",
    section: "Replacement Questions",
    severity: "required",
    kind: "label_value",
    requiredDocument: "individual_application",
    expectedPageSubtype: "premium",
    requiredSection: "existing coverage|section e|replacement",
    evidence: ["value", "checkbox"],
    labelPatterns: ["existing coverage", "replacement", "section e"],
    valuePatterns: ["replacement|existing coverage|yes|no"],
    locationKey: "existingCoverage",
    confidenceThreshold: 0.85,
  },
  {
    id: "beneficiary",
    label: "Beneficiary Designation",
    section: "Beneficiary Designation",
    severity: "required",
    kind: "label_value",
    requiredDocument: "individual_application",
    expectedPageSubtype: "beneficiary",
    requiredSection: "beneficiary|section f",
    evidence: ["value"],
    labelPatterns: ["beneficiary designation", "primary beneficiary", "contingent beneficiary"],
    valuePatterns: ["beneficiary|primary beneficiary|share %|relationship"],
    locationKey: "beneficiaryDesignation",
    confidenceThreshold: 0.85,
  },

  // ── Application Signatures ─────────────────────────────────────────────────
  {
    id: "owner-signature",
    label: "Owner Signature",
    section: "Signatures",
    severity: "required",
    kind: "signature",
    requiredDocument: "individual_application",
    expectedPageSubtype: "signatures",
    requiredSection: "section i|owner.{0,30}signature",
    evidence: ["signature"],
    signatureLabel: "owner_signature",
    locationKey: "ownerSignature",
    confidenceThreshold: 0.85,
  },
  {
    id: "owner-signature-date",
    label: "Owner Signature Date",
    section: "Signatures",
    severity: "required",
    kind: "date_near_label",
    requiredDocument: "individual_application",
    expectedPageSubtype: "signatures",
    requiredSection: "section i|owner.{0,30}signature",
    evidence: ["date"],
    labelPatterns: ["owner.{0,30}signature.{0,20}date", "owner.{0,20}date\\s*signed"],
    locationKey: "ownerSignatureDate",
    confidenceThreshold: 0.8,
  },
  {
    id: "agent-signature",
    label: "Agent Signature",
    section: "Signatures",
    severity: "required",
    kind: "signature",
    requiredDocument: "individual_application",
    expectedPageSubtype: "signatures",
    requiredSection: "section j|agent.{0,30}signature|producer.{0,30}signature",
    evidence: ["signature"],
    signatureLabel: "agent_signature",
    locationKey: "agentSignature",
    confidenceThreshold: 0.85,
  },
  {
    id: "agent-signature-date",
    label: "Agent Signature Date",
    section: "Signatures",
    severity: "required",
    kind: "date_near_label",
    requiredDocument: "individual_application",
    expectedPageSubtype: "signatures",
    requiredSection: "section j|agent.{0,30}signature",
    evidence: ["date"],
    labelPatterns: ["agent.{0,30}signature.{0,20}date", "agent.{0,20}date\\s*signed", "producer.{0,20}date"],
    locationKey: "agentSignatureDate",
    confidenceThreshold: 0.8,
  },

  // ── Product Disclosure / Allocation ───────────────────────────────────────
  {
    id: "pds-signature",
    label: "Product Disclosure Signature",
    section: "Product Disclosure",
    severity: "required",
    kind: "signature",
    requiredDocument: "initial_premium_allocation",
    expectedPageSubtype: "allocation_table",
    requiredSection: "owner statement|disclosure|initial premium allocation",
    evidence: ["signature"],
    signatureLabel: "product_disclosure_signature",
    locationKey: "productDisclosureSignature",
    confidenceThreshold: 0.85,
  },
  {
    id: "pds-signature-date",
    label: "Product Disclosure Signature Date",
    section: "Product Disclosure",
    severity: "required",
    kind: "date_near_label",
    requiredDocument: "initial_premium_allocation",
    expectedPageSubtype: "allocation_table",
    requiredSection: "owner statement|disclosure|initial premium allocation",
    evidence: ["date"],
    labelPatterns: ["disclosure.{0,20}date", "owner.{0,20}date", "signature.{0,15}date"],
    locationKey: "productDisclosureSignatureDate",
    confidenceThreshold: 0.8,
  },
  {
    id: "allocation-page",
    label: "Initial Premium Allocation Form",
    section: "Initial Premium Allocation",
    severity: "required",
    kind: "page_type",
    requiredDocument: "initial_premium_allocation",
    expectedPageSubtype: "allocation_table",
    requiredSection: "initial premium allocation.{0,25}required",
    evidence: ["page_type"],
    locationKey: "initialPremiumAllocation",
    confidenceThreshold: 0.9,
  },
  {
    id: "allocation-100",
    label: "Allocation Total Equals 100%",
    section: "Initial Premium Allocation",
    severity: "required",
    kind: "allocation_100",
    requiredDocument: "initial_premium_allocation",
    expectedPageSubtype: "allocation_table",
    requiredSection: "initial premium allocation.{0,25}required",
    evidence: ["value"],
    locationKey: "allocationTotalEquals100",
    confidenceThreshold: 0.9,
  },

  // ── Financial Needs Analysis ─────────────────────────────────────────────
  {
    id: "fna-page-1",
    label: "Financial Needs Analysis (Page 1)",
    section: "Financial Needs Analysis",
    severity: "required",
    kind: "page_type",
    requiredDocument: "financial_needs_analysis",
    expectedPageSubtype: "suitability",
    requiredSection: "financial needs analysis",
    evidence: ["page_type"],
    locationKey: "financialNeedsAnalysis",
    confidenceThreshold: 0.85,
  },
  {
    id: "fna-risk",
    label: "Risk Tolerance",
    section: "Financial Needs Analysis",
    severity: "required",
    kind: "label_value",
    requiredDocument: "financial_needs_analysis",
    expectedPageSubtype: "suitability",
    requiredSection: "risk tolerance|question 6",
    evidence: ["value", "checkbox"],
    labelPatterns: ["risk tolerance", "conservative", "moderate", "aggressive"],
    valuePatterns: ["risk tolerance|conservative|moderate|aggressive"],
    locationKey: "riskTolerance",
    confidenceThreshold: 0.85,
  },
  {
    id: "fna-source",
    label: "Source of Funds",
    section: "Financial Needs Analysis",
    severity: "required",
    kind: "label_value",
    requiredDocument: "financial_needs_analysis",
    expectedPageSubtype: "objectives",
    requiredSection: "source of funds|question 16",
    evidence: ["value", "checkbox"],
    labelPatterns: ["source of funds"],
    valuePatterns: ["source of funds|savings|rollover|inheritance|other"],
    locationKey: "sourceOfFunds",
    confidenceThreshold: 0.85,
  },
  {
    id: "fna-distribution",
    label: "Distribution Objectives",
    section: "Financial Needs Analysis",
    severity: "required",
    kind: "label_value",
    requiredDocument: "financial_needs_analysis",
    expectedPageSubtype: "objectives",
    requiredSection: "distribution objectives|question 13",
    evidence: ["value"],
    labelPatterns: ["distribution objectives", "distribution method"],
    valuePatterns: ["distribution objectives|distribution method|income|growth"],
    locationKey: "distributionObjectives",
    confidenceThreshold: 0.85,
  },
  {
    id: "fna-source-other-explain",
    label: "Source of Funds — Other Explanation",
    section: "Financial Needs Analysis",
    severity: "required",
    kind: "label_value",
    requiredDocument: "financial_needs_analysis",
    expectedPageSubtype: "objectives",
    requiredSection: "source of funds|other",
    evidence: ["value"],
    labelPatterns: ["other.{0,30}explain", "specify", "please explain"],
    valuePatterns: ["explain|specify|rollover|transfer"],
    locationKey: "sourceOfFunds",
    condition: { dependsOn: "source_of_funds_other", whenTruthy: true },
    confidenceThreshold: 0.8,
  },

  // ── Agent / Producer Disclosure ────────────────────────────────────────────
  {
    id: "agent-disclosure",
    label: "Insurance Agent/Producer Disclosure",
    section: "Agent/Producer Disclosure",
    severity: "required",
    kind: "page_type",
    requiredDocument: "agent_disclosure",
    expectedPageSubtype: "generic",
    requiredSection: "insurance agent|producer disclosure|agent disclosure",
    evidence: ["page_type"],
    locationKey: "agentProducerDisclosure",
    confidenceThreshold: 0.85,
  },
  {
    id: "acknowledgments",
    label: "Acknowledgments and Signatures",
    section: "Acknowledgments",
    severity: "required",
    kind: "page_type",
    requiredDocument: "agent_disclosure",
    expectedPageSubtype: "generic",
    requiredSection: "acknowledgments and signatures|statement of purchaser",
    evidence: ["page_type", "signature"],
    locationKey: "acknowledgmentsAndSignatures",
    confidenceThreshold: 0.85,
  },

  // ── Conditional: Replacement / Transfer ────────────────────────────────────
  {
    id: "replacement-notice",
    label: "Replacement Notice",
    section: "Replacement",
    severity: "required",
    kind: "page_type",
    requiredDocument: "replacement_notice",
    expectedPageSubtype: "generic",
    requiredSection: "replacement notice|important notice",
    evidence: ["page_type", "value"],
    labelPatterns: ["replacement notice", "section e", "existing coverage"],
    valuePatterns: ["replacement\\s*=\\s*yes|existing coverage|replacing"],
    locationKey: "replacementQuestions",
    condition: { dependsOn: "replacement", whenTruthy: true },
    confidenceThreshold: 0.85,
  },
  {
    id: "disclosure-comparison",
    label: "Disclosure & Comparison of Products",
    section: "Replacement",
    severity: "required",
    kind: "page_type",
    requiredDocument: "disclosure_comparison",
    expectedPageSubtype: "generic",
    requiredSection: "comparison of products|disclosure.{0,20}comparison",
    evidence: ["page_type", "value"],
    labelPatterns: ["comparison of products", "disclosure and comparison", "existing vs proposed"],
    valuePatterns: ["comparison|existing.{0,20}proposed|surrender"],
    locationKey: "disclosureComparison",
    condition: { dependsOn: "replacement", whenTruthy: true },
    confidenceThreshold: 0.85,
  },
  {
    id: "transfer-form",
    label: "Transfer / 1035 Exchange Form",
    section: "Transfer / 1035",
    severity: "required",
    kind: "page_type",
    requiredDocument: "transfer_1035",
    expectedPageSubtype: "transfer_page_1",
    requiredSection: "1035|transfer request|transfer authorization",
    evidence: ["page_type", "value"],
    labelPatterns: ["1035 exchange", "transfer request", "transfer authorization", "relinquishing"],
    valuePatterns: ["1035|transfer|relinquishing|surrendering company"],
    locationKey: "transfer",
    condition: { dependsOn: "transfer_1035", whenTruthy: true },
    confidenceThreshold: 0.85,
  },

  // ── Supporting forms (recommended — not blocking submission) ───────────────
  {
    id: "electronic-transactions",
    label: "Electronic Transactions and Disclosures Agreement",
    section: "Electronic Delivery",
    severity: "recommended",
    kind: "page_type",
    requiredDocument: "electronic_delivery",
    expectedPageSubtype: "generic",
    requiredSection: "electronic transactions|electronic delivery",
    evidence: ["page_type"],
    locationKey: "electronicTransactions",
    confidenceThreshold: 0.8,
  },
  {
    id: "hold-issue",
    label: "Authorization to Hold Issue for Multiple Premiums",
    section: "Hold Issue",
    severity: "recommended",
    kind: "page_type",
    requiredDocument: "hold_issue",
    expectedPageSubtype: "generic",
    requiredSection: "authorization to hold issue|hold issue",
    evidence: ["page_type"],
    locationKey: "authorizationHoldIssue",
    confidenceThreshold: 0.8,
  },
  {
    id: "trail-commission",
    label: "Trail Commission Election",
    section: "Commission Election",
    severity: "recommended",
    kind: "page_type",
    requiredDocument: "commission_election",
    expectedPageSubtype: "generic",
    requiredSection: "trail commission|commission election|commission payment option",
    evidence: ["page_type"],
    locationKey: "trailCommissionElection",
    confidenceThreshold: 0.8,
  },
  {
    id: "privacy-notice",
    label: "Privacy Notice",
    section: "Administrative",
    severity: "recommended",
    kind: "page_type",
    requiredDocument: "administrative",
    expectedPageSubtype: "privacy_notice",
    requiredSection: "privacy notice|privacy policy",
    evidence: ["page_type"],
    locationKey: "privacyNotice",
    includeAdministrativePages: true,
    confidenceThreshold: 0.75,
  },

  // ── Image-only packet overlay (supplemental guidance for scanned packets) ──
  {
    id: "packet-form-fax-confirmation",
    label: "Fax Confirmation / Supporting Documents",
    section: "Packet Forms Review",
    severity: "recommended",
    kind: "page_type",
    requiredDocument: "administrative",
    expectedPageSubtype: "fax_confirmation",
    requiredSection: "fax confirmation|transmission report|scanner report",
    evidence: ["page_type"],
    locationKey: "faxConfirmation",
    includeAdministrativePages: true,
    imageOnlyOverlay: true,
    confidenceThreshold: 0.7,
  },
];

export const EQUITRUST_CORE_RULE_IDS = EQUITRUST_CONFIGURABLE_RULES.filter(
  (rule) => !rule.imageOnlyOverlay
).map((rule) => rule.id);

export const EQUITRUST_IMAGE_ONLY_OVERLAY_RULE_IDS = EQUITRUST_CONFIGURABLE_RULES.filter(
  (rule) => rule.imageOnlyOverlay
).map((rule) => rule.id);
